/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright held by original author
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Class
    varSatPoroSolid

Description
    Solver for partially saturated poro-elasto-plasticity.
    The bishop effective stress principle is use.
    
    We start the timeloop in which we update the coupling terms
    and first evolve the poroFluid solver, then evolve the 
    solid solver.

    The coupling from solid to fluid works by adding a 
    fvOption (poroSolidToFluidCouplingSource Class)
    to the fvOption list of the poroFluid object and 
    provide functions (explicit/implicitCouplingDtoP)
    that the fvOption accesses and adds it to the fluid 
    function.

    The coulpling from fluid to solid is handled by the
    wrapping class (varSatPoroMechanicalLaw)
    around the solid mechanicalLaws. All it needs is to be able 
    to find a scalar field named p or p_rgh on the solid mesh/registry

Author
    Denis Maier, BAW. All rights reserved.
    Héctor Mentenegro, BAW. All rights reserved.

SourceFiles
    varSatPoroSolid.C

\*---------------------------------------------------------------------------*/

#ifndef varSatPoroSolid_H
#define varSatPoroSolid_H

#include "poroSolidInterface.H"
#include "varSatPoroHydraulicModel.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

    namespace poroSolidInteractions
    {

        /*---------------------------------------------------------------------------*\
                        Class varSatPoroSolid Declaration
\*---------------------------------------------------------------------------*/

        class varSatPoroSolid
            : public poroSolidInterface
        {
            // Private data

            //- Field for stabilization procedure for groundwater equation
            autoPtr<volScalarField> fixedStressStabil_;
            //- porosity change, which couples deformation into the flow equation
            autoPtr<volScalarField> nDot_;
            //- flow induced by solid acceleration, which couples deformation into the flow equation
            autoPtr<surfaceVectorField> q_relAcc_;
            //- momentum transfer from fluid to solid
            autoPtr<volScalarField> pRghSolidMesh_;
            //- momentum transfer from fluid to solid
            autoPtr<volScalarField> pSolidMesh_;
            //- Saturation for effective stress calculation
            autoPtr<volScalarField> SSolidMesh_;
            //- porosity for total density calculation
            autoPtr<volScalarField> nSolidMesh_;
            //- water specific weight (used when head based poroFluid
            //  to convert from and two pressure)
            dimensionedScalar magGammaW_;

            //- fluxes arising from differencial acceleration (usually not significant)
            tmp<surfaceVectorField> q_relAcc(const surfaceScalarField& kf, const volVectorField& U);

            // Private Member Functions

            //- Disallow default bitwise copy construct
            varSatPoroSolid(const varSatPoroSolid &);

            //- Disallow default bitwise assignment
            void operator=(const varSatPoroSolid &);

        protected:

        public:
            //- Runtime type information
            TypeName("varSatPoroSolid");

            // Constructors
            //- Construct from components
            varSatPoroSolid(
                Time &runTime,
                const word &region = "poroFluid");

            // Destructor

            virtual ~varSatPoroSolid()
            {
            }

            // Member Functions

            // Edit

            //- Evolve the solid solver and solve the mathematical model
            virtual bool evolve();

            // Access

            //- explicit coupling terms
            virtual const tmp<volScalarField>  explicitCouplingDtoP() const;
            //- explicit coupling terms (get multiplied with pField)
            virtual const tmp<volScalarField>  implicitCouplingDtoP() const; 

            virtual void writeFields(const Time &runTime);

        };

        // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

    } // namespace solidModels

    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
