#!/usr/bin/env python3
from pathlib import Path
import re

repo = Path(__file__).resolve().parents[1]
s4f = repo / "external" / "solids4foam"
src_root = s4f / "src"
models_root = src_root / "solids4FoamModels"

seed_dirs = [
    models_root / "physicsModels",
    models_root / "solidModels",
    models_root / "materialModels",
]

if not s4f.exists():
    raise SystemExit("Missing external/solids4foam checkout. Add the solids4foam v2.3 submodule first.")

include_re = re.compile(r'^\s*#\s*include\s*["<]([^">]+)[">]')

headers_by_name = {}
sources_by_stem = {}
for p in src_root.rglob('*'):
    if p.suffix in {'.H', '.hpp'}:
        headers_by_name.setdefault(p.name, []).append(p)
    elif p.suffix == '.C':
        sources_by_stem.setdefault(p.stem, []).append(p)


def parse_includes(path: Path):
    out = []
    try:
        txt = path.read_text(errors='ignore')
    except Exception:
        return out
    for line in txt.splitlines():
        m = include_re.match(line)
        if m:
            out.append(m.group(1).split('/')[-1])
    return out


visited_headers = set()
selected_sources = set()
queue = []

for d in seed_dirs:
    for c in d.rglob('*.C'):
        selected_sources.add(c)
        h = c.with_suffix('.H')
        if h.exists():
            queue.append(h)

while queue:
    h = queue.pop()
    if h in visited_headers:
        continue
    visited_headers.add(h)

    for inc in parse_includes(h):
        for hp in headers_by_name.get(inc, []):
            if hp not in visited_headers:
                queue.append(hp)
            for cp in sources_by_stem.get(hp.stem, []):
                if cp not in selected_sources:
                    selected_sources.add(cp)
                    ch = cp.with_suffix('.H')
                    if ch.exists() and ch not in visited_headers:
                        queue.append(ch)

for c in list(selected_sources):
    for inc in parse_includes(c):
        for hp in headers_by_name.get(inc, []):
            for cp in sources_by_stem.get(hp.stem, []):
                selected_sources.add(cp)

paths = sorted(selected_sources)
out = repo / 'solids4FoamPMF' / 'Make' / 'files'
out.parent.mkdir(parents=True, exist_ok=True)
with out.open('w') as f:
    f.write('// Auto-generated by scripts/generate_solids4foam_pmf_files.py\n\n')
    for p in paths:
        f.write(f"../{p.relative_to(repo)}\\n")
    f.write('\nLIB = $(FOAM_USER_LIBBIN)/libsolids4FoamPMF\n')

print(f"Wrote {out} with {len(paths)} sources")
